<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EvaluationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('evaluations')->insert([
            'evaluations_id' => 1,
            'name' => 'SCL 90R',
            'description' => 'Instrucciones: A continuación se le presentarán una serie de 90 síntomas. Por favor indique si ha padecido alguno de dichos síntomas durante la ultima semana y con qué gravedad lo ha sentido.',
        ]);

        // PREGUNTAS LSB 50
        $questions = [
            ['question' => 'Dolores de cabeza', 'category' => 'Somatizaciones'],
            ['question' => 'Nerviosismo', 'category' => 'Ansiedad'],
            ['question' => 'Pensamientos desagradables que no se iban de mi cabeza', 'category' => 'Obsesiones'],
            ['question' => 'Sensación de mareo o desmayo', 'category' => 'Somatizaciones'],
            ['question' => 'Falta de interés en relaciones sexuales', 'category' => 'Depresión'],
            ['question' => 'Criticar a los demás', 'category' => 'Sens. Interper'],
            ['question' => 'Senstir que otro puede controlar mis pensamientos', 'category' => 'Psicoticismo'],
            ['question' => 'Sentir que otros son culpables de lo que me pasa', 'category' => 'Paranoia'],
            ['question' => 'Tener dificultad para memorizar cosas', 'category' => 'Obsesiones'],
            ['question' => 'Estar preocupado por mi falta de ganas ára hacer algo', 'category' => 'Obsesiones'],
            ['question' => 'Sentirme enojado, malhumorado', 'category' => 'Hostilidad'],
            ['question' => 'Dolores en el pecho', 'category' => 'Somatizaciones'],
            ['question' => 'Miedo a los espacios abiertos o a las calles', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentirme con muy pocas energías', 'category' => 'Depresión'],
            ['question' => 'Pensar en quitarme la vida', 'category' => 'Depresión'],
            ['question' => 'Escuchar voces que otras personas no oyen', 'category' => 'Psicoticismo'],
            ['question' => 'Temblores en mi cuerpo', 'category' => 'Ansiedad'],
            ['question' => 'Pender la confianza en la mayoría de las personas', 'category' => 'Paranoia'],
            ['question' => 'No tener ganas de comer', 'category' => 'Items Adicionales'],
            ['question' => 'Llorar por cualquier cosa', 'category' => 'Depresión'],
            ['question' => 'Sentirme incómodo con personas del otro sexo', 'category' => 'Sens. Interper'],
            ['question' => 'Sentirme atrapado o encerrado', 'category' => 'Depresión'],
            ['question' => 'Asustarme de repente sin razón alguna', 'category' => 'Ansiedad'],
            ['question' => 'Explotar y no poder controlarme', 'category' => 'Hostilidad'],
            ['question' => 'Tener miedo a salir solo de mi casa', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentirme culpable por cosas que ocurren', 'category' => 'Depresión'],
            ['question' => 'Dolores en la espalda', 'category' => 'Somatizaciones'],
            ['question' => 'No poder terminar las cosas que empecé a hacer', 'category' => 'Obsesiones'],
            ['question' => 'Sentirme solo', 'category' => 'Depresión'],
            ['question' => 'Sentirme triste', 'category' => 'Depresión'],
            ['question' => 'Preocuparme demasiado por todo lo que pasa', 'category' => 'Depresión'],
            ['question' => 'No tener interés por nada', 'category' => 'Depresión'],
            ['question' => 'Tener miedos', 'category' => 'Ansiedad'],
            ['question' => 'Sentirme herido en mis sentimientos', 'category' => 'Sens. Interper'],
            ['question' => 'Creer que la gente sabe que estoy pensando', 'category' => 'Psicoticismo'],
            ['question' => 'Sentir que no me comprenden', 'category' => 'Sens. Interper'],
            ['question' => 'Sentir que no le caigo bien a la gente, que no les gusto', 'category' => 'Sens. Interper'],
            ['question' => 'Tener que hacer las cosas muy despacio para estar seguro de que están bien hechas', 'category' => 'Obsesiones'],
            ['question' => 'Mi corazón late muy fuerte, se acelera', 'category' => 'Ansiedad'],
            ['question' => 'Náuseas o dolor de estómago', 'category' => 'Somatizaciones'],
            ['question' => 'Sentirme inferior a los demás', 'category' => 'Sens. Interper'],
            ['question' => 'Calambres en manos, brazos o piernas', 'category' => 'Somatizaciones'],
            ['question' => 'Sentir que me vigilan o me hablan de mi', 'category' => 'Paranoia'],
            ['question' => 'Tener problemas para dormirme', 'category' => 'Items Adicionales'],
            ['question' => 'Tener que controlar una o más veces lo que hago', 'category' => 'Obsesiones'],
            ['question' => 'Tener dificultades para tomar decisiones', 'category' => 'Obsesiones'],
            ['question' => 'Tener miedo de viajar en tren, omnibus o subterraneos', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Tener dificultades para respirar bien', 'category' => 'Somatizaciones'],
            ['question' => 'Ataques de frío o calor', 'category' => 'Somatizaciones'],
            ['question' => 'Tener que evitar acercarme a algunos lugares o actividades porque me dan miedo', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentir que mi mente queda en blanco', 'category' => 'Obsesiones'],
            ['question' => 'Hormigueos en alguna parte del cuerpo ', 'category' => 'Somatizaciones'],
            ['question' => 'Tener un nudo en la garganta', 'category' => 'Somatizaciones'],
            ['question' => 'Perder las esperanzas en el futuro', 'category' => 'Depresión'],
            ['question' => 'Dificultades para concentrarme en lo que estoy haciendo', 'category' => 'Obsesiones'],
            ['question' => 'Sentir flojedad, debilidad en partes de mi cuerpo', 'category' => 'Somatizaciones'],
            ['question' => 'Sentirme muy nervioso o agitado', 'category' => 'Ansiedad'],
            ['question' => 'Sentir mis brazos y piernas muy pesados', 'category' => 'Somatizaciones'],
            ['question' => 'Pensar que me estoy por morir', 'category' => 'Items Adicionales'],
            ['question' => 'Comer demasiado', 'category' => 'Items Adicionales'],
            ['question' => 'Sentirme incómodo cuando me miran o hablan de mi', 'category' => 'Sens. Interper'],
            ['question' => 'Tener ideas pensamientos que no son los mios', 'category' => 'Psicoticismo'],
            ['question' => 'Necesitar golpear o lastimar a alguien', 'category' => 'Hostilidad'],
            ['question' => 'Despertarme muy temprano por la mañana sin necesidad', 'category' => 'Items Adicionales'],
            ['question' => 'Repetir muchas veces algo que hago: Contar, lavarme, contar cosas', 'category' => 'Obsesiones'],
            ['question' => 'Dormis con problemas, muy inquieto', 'category' => 'Items Adicionales'],
            ['question' => 'Necesitar romper o destrozar cosas', 'category' => 'Hostilidad'],
            ['question' => 'Tener ideas, pensamientos que los demás no entienden', 'category' => 'Paranoia'],
            ['question' => 'Estar muy pendiente de lo que los demás puedan pensar de mi', 'category' => 'Sens. Interper'],
            ['question' => 'Sentirme incómodo en lugares donde hay mucha gente', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentir que todo me cuesta mucho esfuerzo', 'category' => 'Depresión'],
            ['question' => 'Tener ataques de mucho miedo o de pánico', 'category' => 'Ansiedad'],
            ['question' => 'Sentirme mal si estoy comiendo o bebiendo en público', 'category' => 'Sens. Interper'],
            ['question' => 'Meterme muy seguido en discusiones', 'category' => 'Hostilidad'],
            ['question' => 'Poenerme nervioso cuando estoy solo', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentir que los demás no me valoran como merezco', 'category' => 'Paranoia'],
            ['question' => 'Sentirme solo, aún estando con gente', 'category' => 'Psicoticismo'],
            ['question' => 'Estar inquieto, no poder estar sentado sin moverme', 'category' => 'Ansiedad'],
            ['question' => 'Sentirme un inutil', 'category' => 'Depresión'],
            ['question' => 'Sentir que algo malo me va a pasar', 'category' => 'Ansiedad'],
            ['question' => 'Gritar o tirar las cosas', 'category' => 'Hostilidad'],
            ['question' => 'Miedo a desmayarme en medio de la gente', 'category' => 'Ansiedad Fóbica'],
            ['question' => 'Sentir que se aprovechan de mí si los dejo', 'category' => 'Paranoia'],
            ['question' => 'Pensar cosas sobre el sexo que me molesta', 'category' => 'Psicoticismo'],
            ['question' => 'Sentir que debo ser castigado por mis pecados', 'category' => 'Psicoticismo'],
            ['question' => 'Tener imágenes o pensamientos que me dan miedo', 'category' => 'Ansiedad'],
            ['question' => 'Sentir que algo anda mal en mi cuerpo', 'category' => 'Psicoticismo'],
            ['question' => 'Sentirme alejado de las demás personas', 'category' => 'Psicoticismo'],
            ['question' => 'Sentirme culpable', 'category' => 'Items Adicionales'],
            ['question' => 'Pensar que en mi cabeza hay algo que no funciona bien', 'category' => 'Psicoticismo'],
        ];

        foreach ($questions as $question) {
            DB::table('evaluations_questions')->insert([
                'evaluations_id' => 1,
                'question' => $question['question'],
                'category' => $question['category'],
                'type' => 1,
                'default_value' => null,
                'inverse' => false,
            ]);
        }

        // ------
        DB::table('patients_evaluations')->insert([
            'evaluations_id' => 1,
            'guid' => '4b533a8d-6b87-4d9a-a84f-4f723dfa64f4',
            'reference' => '35201786',
            'gender' => 'MALE',
            'created_at' => date('Y-m-d H:i:s'),
        ]);

        // ---------- Escala de sintomas III

        DB::table('evaluations')->insert([
            'evaluations_id' => 2,
            'name' => 'SIMS',
            'description' => 'FALTANTE',
        ]);

        $questions2 = [
            ['question' => 'Puedo recordar que es lo que hice hace una hora', 'category' => 'Amnésia', 'inverse' => true],
            ['question' => 'Tengo dificultades para recordar la direccion en la que vivo', 'category' => 'Amnésia'],
            ['question' => 'El mayor problema que tengo es mi memoria', 'category' => 'Amnésia'],
            ['question' => 'Últimamente me he dado cuenta de que mi memoria ha empeorado tanto que a habido dias enteros que no consigo recordar', 'category' => 'Amnésia'],
            ['question' => 'En ocasiones he sido incapaz de recordar los nombres o las caras de familiares cercanos, de forma que me resultan unos completos extraños', 'category' => 'Amnésia'],
            ['question' => 'Tengo dificultades para recordar el dia de la semana', 'category' => 'Amnésia'],
            ['question' => 'Tengo dificultades para recordar que fecha es hoy', 'category' => 'Amnésia'],
            ['question' => 'Mi vida pasada y acontecimientos importantes se vuelven borrosos durante la noche', 'category' => 'Amnésia'],
            ['question' => 'Tengo dificultades para recordar mi numero de telefono', 'category' => 'Amnésia'],
            ['question' => 'No puedo recordar si estoy casado o no', 'category' => 'Amnésia'],
            ['question' => 'Me hicieron un comentario sobre una reunión en la que me mostré enfadado con alguien pero no lo recuerdo en absoluto', 'category' => 'Amnésia'],
            ['question' => 'Aveces olvido como llegar a casa mientras conduzco', 'category' => 'Amnésia'],
            ['question' => 'Cuando no puedo recordar algo, las instrucciones o consejos no me sirven de ayuda', 'category' => 'Amnésia'],
            ['question' => 'Tengo dificultades para recordar el día de mi cumpleaños', 'category' => 'Amnésia'],
            ['question' => 'Tengo dolores de cabeza y mareos justo cuando olvido algo', 'category' => 'Amnésia'],
            ['question' => 'Si su sombra apunta hasta el sureste, el sol esta situado en el noreste del cielo', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'El oro y la plata son similares porque ambos son metales', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'LA capital de ITALIA es HUNGRIA', 'category' => 'Bajo CI'],
            ['question' => 'BARCELONA es la Capital de España', 'category' => 'Bajo CI'],
            ['question' => 'Una semana tiene seis dias', 'category' => 'Bajo CI'],
            ['question' => 'No puedo contar hacia atrás de 20 de a 1 sin cometer errores', 'category' => 'Bajo CI'],
            ['question' => 'Las velas que se encienden estan hechas de cera', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'Un juez y un abogado son similares puesto que ambos son parte del sistema legal', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'Una puerta y una reja son similares porque ambas se abren', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'Cristobal Colon descubrio America', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'Si ud. tiene 1,50 pesos y gasta cincuenta centavos le quedan setentaycinco centavos', 'category' => 'Bajo CI'],
            ['question' => 'En la serie 1 - 12 - 123, la siguiente respuesta es 456', 'category' => 'Bajo CI', 'inverse' => true],
            ['question' => 'El mayor problema que tengo es que las cosas son dificiles de entender para mi', 'category' => 'Bajo CI'],
            ['question' => 'Un hombre tiene 56 manzanas y un vecino le regala 37 mas. Ahora tiene 83 manzanas', 'category' => 'Bajo CI'],
            ['question' => 'En la serie 11  - 22 - 33 - la siguiente respuesta seria 44', 'category' => 'Bajo CI'],
            ['question' => 'A veces píerdo la sensibilidad en mi mano de tal forma que siento como si llevara un guante puesto en ella', 'category' => 'Deterioro Neurológico'],
            ['question' => 'La comida no me sabe igual que antes', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Mas de tres veces al día me levanto para agarrar algo, pero olvido que es lo que era', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Mi mayor problema es que mi cerebro esta enfermo', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Caminar me resulta uy dificil debido a mis problemas de equilibrio', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Aveces cuando escribo un numero de telefono, me doy cuenta de que los nnumeros salen al reves aunque yo no lo intente', 'category' => 'Deterioro Neurológico'],
            ['question' => 'En ocaciones mis muscuos se mueven con dificultad sin razon aparente, hasta el punto de que siento mis brazos y piernas como si pesaran una tonelada', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Siento tanto dolor en mi cuerpo que parece como si tuviera bichos andando bajo mi piel', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Siento un zumbido constante en mis oidos', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Tengo dificultades para reconocer palabras escritas o habladas', 'category' => 'Deterioro Neurológico'],
            ['question' => 'No he experimentado cambios en mi sentido del olfato', 'category' => 'Deterioro Neurológico', 'inverse' => true],
            ['question' => 'Siento partes de mis extremidades entumecidas, aunque puedo moverlas sin dificultad', 'category' => 'Deterioro Neurológico'],
            ['question' => 'A veces mis pantorrillas estan entumecidas que soy incapaz de moverlas', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Trabajo muy lentamente y mi rendimiento es muy reducido porque mi capacidad est{a muy limitada', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Una vez a la semana, subitamente, siento frio aunque la temperatura ambiental sea calida', 'category' => 'Deterioro Neurológico'],
            ['question' => 'Creo que el numero de telefono de una persona no se asigna aleatoriamente, sino que es la forma que tiene Dios de decidir quwe persona se salvara', 'category' => 'Psicosis'],
            ['question' => 'ME he dado cuenta de que mi sombra baila como loca incluso cuando me quedo quieto', 'category' => 'Psicosis'],
            ['question' => 'ME he dado cuenta de que mi cuerpo cambia de forma incluso si mi peso no varia', 'category' => 'Psicosis'],
            ['question' => 'No hay nada que pueda hacer, aparte de tomar medicacion, que tenga algun efecto sobre las voces que oigo', 'category' => 'Psicosis'],
            ['question' => 'Creo que el gobierno a instalado camaras de video en las señales de trafico para espiarme', 'category' => 'Psicosis'],
            ['question' => 'La gente introduce pensamientos en mi cabeza en contra de mi voluntad', 'category' => 'Psicosis'],
            ['question' => 'Creo que si uno se concentra muco puede llegar a ver los pensamientos de los otros', 'category' => 'Psicosis'],
            ['question' => 'La voz o voces que oigo, y que otros no oyen, nunca an cesado desde que empezaron', 'category' => 'Psicosis'],
            ['question' => 'Las flores tienen poderes majicos, como hablarle a las personas', 'category' => 'Psicosis'],
            ['question' => 'La voz o voces que oigo, y que otros no oyen, provienen de fuera de mi cabeza', 'category' => 'Psicosis'],
            ['question' => 'Tengo tanto miedo a que alguien me haga daño que se exacatamente como y cuando lo hara', 'category' => 'Psicosis'],
            ['question' => 'Un dia de repente empece a oir una o mas voces que nadie mas oia', 'category' => 'Psicosis'],
            ['question' => 'En mis visiones suelo ver partes de mi cuerpo cubiertas de sangre', 'category' => 'Psicosis'],
            ['question' => 'Cuando oigo voces que parecen provenir de ningun sitio en especial, quiero echar a correr pero me doy cuenta de que no puedo hacerlo sin gran dificultad', 'category' => 'Psicosis'],
            ['question' => 'Cuando oigo voces siento como si salieran de mi cuerpo a traves de mis dientes', 'category' => 'Psicosis'],
            ['question' => 'Cuando mi depresion se agrava, salgo a dar largos paseos y realizo algo de ejercicio para reducir la tension', 'category' => 'Afectividad'],
            ['question' => 'Rara vez me rio', 'category' => 'Afectividad'],
            ['question' => 'Incluso estando deprimido la mayor parte del tiempo, me siento mejor por la mañana tras una buena noche de sueño', 'category' => 'Afectividad'],
            ['question' => 'Mi estado de animo es peor por la noche', 'category' => 'Afectividad'],
            ['question' => 'Aveces etoy tan deprimido que me voy a dormir asta que se me pase esa sensacion', 'category' => 'Afectividad'],
            ['question' => 'Lloro en muy raras ocasiones', 'category' => 'Afectividad', 'inverse' => true],
            ['question' => 'Cuanto ma deprimido me siento mas ganas de comer  me entran', 'category' => 'Afectividad'],
            ['question' => 'Tengo dificultades para dormir', 'category' => 'Afectividad'],
            ['question' => 'Mi estado de animo empeora a medida que pasa el dia', 'category' => 'Afectividad'],
            ['question' => 'No tengo problemas para conciliar el sueño, pero me despierto a menudo durante la noche', 'category' => 'Afectividad'],
            ['question' => 'Me siento deprimido todo el tiempo', 'category' => 'Afectividad'],
            ['question' => 'Me parece que no tengo tanta energia como solia tener', 'category' => 'Afectividad'],
            ['question' => 'Cuando estoy deprimido, me animo con mis amigos, intereses y aficciones', 'category' => 'Afectividad', 'inverse' => true],
            ['question' => 'Parece que no puedo expresar mis sentimientos', 'category' => 'Afectividad'],
            ['question' => 'Aunque las cosas esten realmente mal trato de mantenerme esperanzado hasta que mejoren', 'category' => 'Afectividad', 'inverse' => true],
        ];

        foreach ($questions2 as $question) {
            DB::table('evaluations_questions')->insert([
                'evaluations_id' => 2,
                'question' => $question['question'],
                'category' => $question['category'],
                'type' => 2,
                'default_value' => null,
                'inverse' => $question['inverse'] ?? false,
            ]);
        }

        // ------- CUESTIONARIO DE PERSONALIDAD

        DB::table('evaluations')->insert([
            'evaluations_id' => 3,
            'name' => 'SCID II',
            'description' => 'Estas preguntas son acerca de su personalidad, es decir, la manera en que Ud. se comporta normalmente en su vida habitual. Si la pregunta se adapta a Ud. completamente o en general escriba el número 1, o bien escriba el número 0 si no se adapta a Ud. Si no entiende alguna pregunta o no está seguro de la respuesta, déjela en blanco.',
        ]);

        $questions3 = [
            ['question' => '1. ¿Ha evitado trabajos o tareas en los que tenía que tratar con mucha gente?', 'category' => 'Evitativo'],
            ['question' => '2. ¿Evita entablar relación con otras personas a menos que esté seguro de que les va a caer bien?', 'category' => 'Evitativo'],
            ['question' => '3. ¿Le resulta difícil ser “abierto” aún con las personas que mantiene una relación cercana?', 'category' => 'Evitativo'],
            ['question' => '4. ¿Le preocupa con frecuencia ser criticado/a o rechazado/a en situaciones sociales?', 'category' => 'Evitativo'],
            ['question' => '5. ¿Permanece generalmente callado/a cuando conoce gente nueva?', 'category' => 'Evitativo'],
            ['question' => '6. ¿Cree Ud. que no es bueno/a, listo/a, atractivo/a como la mayoría de las personas?', 'category' => 'Evitativo'],
            ['question' => '7. ¿Le da miedo intentar cosas nuevas?', 'category' => 'Evitativo'],
            ['question' => '8. ¿Necesita dejarse aconsejar por parte de otras personas antes de poder tomar decisiones cotidianas, como qué ropa ponerse, o  qué pedir en un restaurante?', 'category' => 'Dependencia'],
            ['question' => '9. ¿Depende Ud. de otras personas para controlar áreas importantes de su vida, como asuntos económicos, el cuidado de los hijos o decisiones sobre donde y cómo vivir?', 'category' => 'Dependencia'],
            ['question' => '10. ¿Le resulta difícil mostrarse en desacuerdo con otras personas cuando considera que están equivocadas?', 'category' => 'Dependencia'],
            ['question' => '11. ¿Le cuesta empezar a hacer tareas cuando no hay nadie que le ayude?', 'category' => 'Dependencia'],
            ['question' => '12. ¿Se ha ofrecido con frecuencia como voluntario/a para realizar tareas desagradables?', 'category' => 'Dependencia'],
            ['question' => '13. ¿Se siente generalmente incómodo/a  cuando está solo/a?', 'category' => 'Dependencia'],
            ['question' => '14. Cuando finaliza una relación de pareja, ¿siente que tiene que encontrar inmediatamente a otra persona que cuide de Ud.?', 'category' => 'Dependencia'],
            ['question' => '15. ¿Le preocupa mucho ser abandonado/a y tener que cuidar de Ud. mismo/a?', 'category' => 'Dependencia'],
            ['question' => '16. ¿Es Ud. la clase de persona que se fija en los detalles, el orden y la organización y que le gusta hacer listas y agendas?', 'category' => 'Obsesivo'],
            ['question' => '17. ¿Tiene problemas a la hora de finalizar tareas o trabajos debido a que emplea demasiado tiempo tratando de hacer las cosas de forma perfecta?', 'category' => 'Obsesivo'],
            ['question' => '18. ¿Le parece a Ud. o le han dicho que está tan dedicado/a a su trabajo (o estudios) que no le queda tiempo para otra actividad y tiempo para la diversión?', 'category' => 'Obsesivo'],
            ['question' => '19. ¿Tiene Ud. valores muy estrictos sobre lo que está bien y lo que está mal?', 'category' => 'Obsesivo'],
            ['question' => '20. ¿Le cuesta a Ud. mucho tirar las cosas porque algún día podrían serle útiles?', 'category' => 'Obsesivo'],
            ['question' => '21. ¿Le cuesta dejar que otras personas lo/a ayuden a menos que hagan las cosas exactamente como Ud. quiere?', 'category' => 'Obsesivo'],
            ['question' => '22. ¿Le cuesta mucho gastar dinero en Ud. mismo/a o en otros, aún teniendo suficiente?', 'category' => 'Obsesivo'],
            ['question' => '23. ¿Está a menudo tan seguro/a de tener razón que no le importa lo que digan los demás?', 'category' => 'Obsesivo'],
            ['question' => '24. ¿Le han comentado otras personas que es Ud. terco/a o rígido/a?', 'category' => 'Obsesivo'],
            ['question' => '25. Cuando alguien le pide que haga algo que Ud. no quiere hacer, ¿dice si pero luego lo hace despacio o mal?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '26. Cuando no quiere hacer algo, ¿suele simplemente olvidarse de hacerlo?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '27. ¿Siente con frecuencia que los demás no lo/a comprenden o que no aprecian mucho lo que Ud. hace?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '28. ¿Está Ud. a menudo de mal humor y tiende a discutir?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '29. ¿Le ha parecido que la mayoría de sus jefes, profesores, supervisores, médicos y personas supuestamente expertas en realidad no lo son?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '30. ¿Piensa a menudo que no es justo que otra personas tengan más que Ud.?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '31. ¿Se queja a menudo de haber tenido más mala suerte de lo normal?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '32. Cuando alguien le pide hacer algo, ¿se niega Ud. con enojo y luego se siente mal y se disculpa?', 'category' => 'Pasivo-Agresivo'],
            ['question' => '33. ¿Se siente infeliz, o como si la vida no fuese agradable?', 'category' => 'Depresivo'],
            ['question' => '34. ¿Cree Ud. ser una persona incapaz al punto de no sentirse bien consigo mismo?', 'category' => 'Depresivo'],
            ['question' => '35. ¿Se descalifica a sí mismo/a con frecuencia?', 'category' => 'Depresivo'],
            ['question' => '36. ¿Piensa mucho en cosas malas que le han sucedido en el pasado o se preocupa por las que podrían suceder en el futuro?', 'category' => 'Depresivo'],
            ['question' => '37. ¿Juzga a menudo a los demás con dureza y les encuentra defectos con facilidad?', 'category' => 'Depresivo'],
            ['question' => '38. ¿Cree Ud. que la mayoría de las personas no son buenas?', 'category' => 'Depresivo'],
            ['question' => '39. ¿Espera Ud. casi siempre que las cosas le vayan mal?', 'category' => 'Depresivo'],
            ['question' => '40. ¿Se siente Ud. a menudo culpable de cosas que ha hecho o dejado de hacer?', 'category' => 'Depresivo'],
            ['question' => '41. ¿Tiene a menudo que estar alerta para evitar que los demás abusen de Ud. o lo hieran?', 'category' => 'Paranoide'],
            ['question' => '42. ¿Pasa Ud. mucho tiempo preguntándose si puede fiarse de sus amigos o compañeros de trabajo?', 'category' => 'Paranoide'],
            ['question' => '43. ¿Cree que es mejor no dejar que otras personas sepan mucho sobre Ud. porque podrían utilizar la información en su contra?', 'category' => 'Paranoide'],
            ['question' => '44. ¿Detecta a menudo amenazas o insultos ocultos en lo que la gente dice o hace?', 'category' => 'Paranoide'],
            ['question' => '45. ¿Es Ud. la clase de persona que guarda rencor o tarda mucho en perdonar a las personas que de alguna manera lo han agredido?', 'category' => 'Paranoide'],
            ['question' => '46. ¿Hay muchas personas a las que no puede perdonar por algo que le hicieron o le dijeron hace mucho?', 'category' => 'Paranoide'],
            ['question' => '47. ¿Se enoja o se pone furioso/a cuando lo/a critican o insultan?', 'category' => 'Paranoide'],
            ['question' => '48. ¿Ha sospechado a menudo que su pareja le era infiel?', 'category' => 'Paranoide'],
            ['question' => '49. Cuando está en público y ve personas hablando, ¿le parece que están hablando de Ud.?', 'category' => 'Paranoide'],
            ['question' => '50. ¿Le ha parecido con frecuencia que hay cosas que no poseen ningún significado especial para la mayoría de la gente y que sin embargo contienen un mensaje especial para Ud.?', 'category' => 'Esquizotípico'],
            ['question' => '51. Cuando está entre la gente, ¿tiene a menudo la sensación de que lo están observando o mirando fijamente?', 'category' => 'Esquizotípico'],
            ['question' => '52. ¿Ha sentido alguna vez que podría ser que sucedieran cosas simplemente formulando un deseo o pensando en ellas?', 'category' => 'Esquizotípico'],
            ['question' => '53. ¿Ha tenido experiencias personales de tipo sobrenatural?', 'category' => 'Esquizotípico'],
            ['question' => '54. ¿Cree Ud. tener un “sexto sentido” que le permite conocer y predecir cosas que otros no pueden?', 'category' => 'Esquizotípico'],
            ['question' => '55. ¿Le ha parecido a menudo como si los objetos o las sombras fueran personas o animales, o que los ruidos fueran voces de personas?', 'category' => 'Esquizotípico'],
            ['question' => '56. ¿Ha tenido la sensación de que alguna persona o fuerza estaba cerca de Ud. aunque no podía ver a nadie?', 'category' => 'Esquizotípico'],
            ['question' => '57. ¿Ve con frecuencia auras o campos de energía?', 'category' => 'Esquizotípico'],
            ['question' => '58. ¿Hay muy pocas personas a las que se sienta próximo/a aparte de su familia inmediata?', 'category' => 'Esquizoide'],
            ['question' => '59. ¿Se siente nervioso/a cuando está con otras personas?', 'category' => 'Esquizoide'],
            ['question' => '60. ¿Es de poca importancia para Ud. si tiene o no relaciones personales?', 'category' => 'Esquizoide'],
            ['question' => '61. ¿Prefiere Ud. casi siempre arreglárselas solo/a para hacer cosas?', 'category' => 'Esquizoide'],
            ['question' => '62. ¿Podría estar satisfecho/a sin tener jamás ninguna relación sexual con otra persona?', 'category' => 'Esquizoide'],
            ['question' => '63. ¿Hay muy pocas cosas que le den placer?', 'category' => 'Esquizoide'],
            ['question' => '64. ¿Les es indiferente lo que otras personas piensen de Ud.?', 'category' => 'Esquizoide'],
            ['question' => '65. ¿Cree que no hay nada que lo/a pongan ni muy contenta ni muy triste?', 'category' => 'Esquizoide'],
            ['question' => '66. ¿Le gusta ser el centro de atención?', 'category' => 'Histriónico'],
            ['question' => '67. ¿Coquetea mucho?', 'category' => 'Histriónico'],
            ['question' => '68. ¿Se da cuenta a menudo de que se está comportando en forma seductora con otras personas?', 'category' => 'Histriónico'],
            ['question' => '69. ¿Trata de llamar la atención a través de su forma de vestir o su aspecto físico?', 'category' => 'Histriónico'],
            ['question' => '70. ¿Se muestra a menudo como una persona excesivamente expresiva?', 'category' => 'Histriónico'],
            ['question' => '71. ¿Cambia de opinión según las personas con las personas con las que esté según lo que acaba de leer o ver en televisión?', 'category' => 'Histriónico'],
            ['question' => '72. ¿Tiene Ud. muchos amigos a los que se siente próximo/a?', 'category' => 'Histriónico'],
            ['question' => '73. ¿Considera que los demás no saben apreciar su talento o sus cualidades?', 'category' => 'Narcisista'],
            ['question' => '74. ¿Le han comentado otros que Ud. tiene una opinión demasiado elevada de sí mismo?', 'category' => 'Narcisista'],
            ['question' => '75. ¿Piensa frecuentemente que algún día alcanzará el poder, la fama o el reconocimiento?', 'category' => 'Narcisista'],
            ['question' => '76. ¿Pasa Ud. mucho tiempo pensando que algún día disfrutará del romance perfecto?', 'category' => 'Narcisista'],
            ['question' => '77. Cuando tiene un problema, ¿insiste casi siempre en ver al máximo responsable?', 'category' => 'Narcisista'],
            ['question' => '78. ¿Considera Ud. que es importante dedicar el tiempo a personas especiales o influyentes?', 'category' => 'Narcisista'],
            ['question' => '79. ¿Es muy importante para Ud. que la gente le preste atención, lo/a admire de alguna manera?', 'category' => 'Narcisista'],
            ['question' => '80. Si ciertas reglas o convenciones sociales se vuelven un obstáculo en su camino, ¿Ud. deja de respetarlas?', 'category' => 'Narcisista'],
            ['question' => '81. ¿Considera Ud. ser un tipo de persona que merece un trato especial?', 'category' => 'Narcisista'],
            ['question' => '82. ¿Le resulta necesario aprovecharse de otros para conseguir lo que quiere?', 'category' => 'Narcisista'],
            ['question' => '83. ¿Tiene con frecuencia que anteponer sus necesidades a las de otras personas?', 'category' => 'Narcisista'],
            ['question' => '84. ¿Espera que otros hagan lo que Ud. les pide sin dudar por ser Ud. quien es?', 'category' => 'Narcisista'],
            ['question' => '85. ¿Le interesan a Ud. los problemas y los sentimientos de los demás?', 'category' => 'Narcisista'],
            ['question' => '86. ¿Se han quejado otros de que Ud. no los escucha o ni se preocupa por sus sentimientos?', 'category' => 'Narcisista'],
            ['question' => '87. ¿Tiene envidia de otras personas?', 'category' => 'Narcisista'],
            ['question' => '88. ¿Cree Ud. que los demás lo/a envidian a Ud.?', 'category' => 'Narcisista'],
            ['question' => '89. ¿Le parece que hay pocas personas que merezcan su tiempo y atención?', 'category' => 'Narcisista'],
            ['question' => '90. ¿Se enfurece cuando ha creído que alguien a quien Ud. Realmente quería iba a abandonarlo?', 'category' => 'Límite'],
            ['question' => '91. Las relaciones con las personas que quiere, ¿Tienen muchos altibajos extremos?', 'category' => 'Límite'],
            ['question' => '92. ¿Cambia imprevistamente su sentido de quién es Ud. o hacia dónde va?', 'category' => 'Límite'],
            ['question' => '93. ¿Cambia dramáticamente su sentido de quién es?', 'category' => 'Límite'],
            ['question' => '94. ¿Es Ud. distinto/a con diferentes personas o en situaciones variadas?', 'category' => 'Límite'],
            ['question' => '95. ¿Se han producido muchos cambios bruscos en sus metas, planes profesionales, creencias religiosas, etc?', 'category' => 'Límite'],
            ['question' => '96. ¿Ha hecho a menudo cosas impulsivamente?', 'category' => 'Límite'],
            ['question' => '97. ¿Ha tratado de hacerse daño o matarse, o ha amenazado con hacerlo?', 'category' => 'Límite'],
            ['question' => '98. ¿Alguna vez se ha cortado, quemado o herido a propósito?', 'category' => 'Límite'],
            ['question' => '99. ¿Experimenta muchos cambios bruscos de estado de ánimo?', 'category' => 'Límite'],
            ['question' => '100. ¿Se siente con frecuencia vacío/a por dentro?', 'category' => 'Límite'],
            ['question' => '101. ¿Tiene Ud. a menudo arranques de bronca o se enfurece tanto que pierde el control?', 'category' => 'Límite'],
            ['question' => '102. Cuando se enoja, ¿golpea Ud. a las personas o arroja objetos?', 'category' => 'Límite'],
            ['question' => '103. ¿Se pone muy furioso por cosas sin importancia?', 'category' => 'Límite'],
            ['question' => '104. Cuando se halla bajo una gran tensión,  ¿se vuelve desconfiado/a con otras personas y se aleja de ellas?', 'category' => 'Límite'],
            ['question' => '105. Antes de los 15 años, ¿atemorizaba o amenazaba a otros niños?', 'category' => 'Antisocial'],
            ['question' => '106. Antes de los 15 años, ¿provocaba Ud. peleas?', 'category' => 'Antisocial'],
            ['question' => '107. Antes de los 15 años, ¿hirió o amenazó a alguien con una arma, como por ejemplo un palo, una piedra, una botella rota, una navaja o una pistola?', 'category' => 'Antisocial'],
            ['question' => '108. Antes de los 15 años, ¿torturó a alguien o le causó dolor y sufrimiento físico?', 'category' => 'Antisocial'],
            ['question' => '109. Antes de los 15 años, ¿torturó o hirió animales a propósito?', 'category' => 'Antisocial'],
            ['question' => '110. Antes de los 15 años, ¿robó, atracó o arrebató por la fuerza algo a alguien amenazándole?', 'category' => 'Antisocial'],
            ['question' => '111. Antes de los 15 años, ¿forzó a alguien a tener relaciones sexuales, a desvestirse delante de Ud. o tocarle sexualmente?', 'category' => 'Antisocial'],
            ['question' => '112. Antes de los 15 años, ¿provocó algún incendio?', 'category' => 'Antisocial'],
            ['question' => '113. Antes de los 15 años, ¿destruyó cosas que no eran suyas?', 'category' => 'Antisocial'],
            ['question' => '114. Antes de los 15 años, ¿mentía mucho o estafaba a otras personas?', 'category' => 'Antisocial'],
            ['question' => '115. Antes de los 15 años, ¿irrumpió en casas, otros edificios o coches de otras personas?', 'category' => 'Antisocial'],
            ['question' => '116. Antes de los 15 años, ¿robaba cosas (sin enfrentarse con la víctima), o falsificaba la firma de otras personas?', 'category' => 'Antisocial'],
            ['question' => '117. Antes de los 15 años, ¿se escapó de casa y pasó la noche fuera?', 'category' => 'Antisocial'],
            ['question' => '118. Antes de los 13 años, ¿permanecía mucho tiempo fuera de casa y llegaba mucho más tarde de la hora permitida?', 'category' => 'Antisocial'],
            ['question' => '119. Antes de los 13 años, ¿faltaba a menudo a clase?', 'category' => 'Antisocial'],
        ];

        foreach ($questions3 as $question) {
            DB::table('evaluations_questions')->insert([
                'evaluations_id' => 3,
                'question' => $question['question'],
                'category' => $question['category'],
                'type' => 3,
                'default_value' => null,
                'inverse' => false,
            ]);
        }
    }
}
